services:

  smartmeter0:
    image: jsandeuc3m/smartmeter:latest
    environment:
      - SM_ID=0
      - SM_IP=10.0.100.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORTV=10000
      - S_PORTI=20000
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.100.1

  circuitbreaker0:
    image: jsandeuc3m/circuitbreaker:latest
    environment:
      - CB_ID=0
      - CB_IP=10.0.100.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30000
    networks:
      transportNetwork:
        ipv4_address: 10.0.100.2

  smartmeter1:
    image: jsandeuc3m/smartmeter:latest
    environment:
      - SM_ID=1
      - SM_IP=10.0.1.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORTV=10010
      - S_PORTI=20010
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.1.1

  circuitbreaker1:
    image: jsandeuc3m/circuitbreaker:latest
    environment:
      - CB_ID=1
      - CB_IP=10.0.1.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30001
    networks:
      transportNetwork:
        ipv4_address: 10.0.1.2

  smartmeter2:
    image: jsandeuc3m/smartmeter:latest
    environment:
      - SM_ID=2
      - SM_IP=10.0.2.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORTV=10020
      - S_PORTI=20020
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.2.1

  circuitbreaker2:
    image: jsandeuc3m/circuitbreaker:latest
    environment:
      - CB_ID=2
      - CB_IP=10.0.2.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30002
    networks:
      transportNetwork:
        ipv4_address: 10.0.2.2

  smartmeter3:
    image: jsandeuc3m/smartmeter:latest
    environment:
      - SM_ID=3
      - SM_IP=10.0.3.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORTV=10030
      - S_PORTI=20030
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.3.1

  circuitbreaker3:
    image: jsandeuc3m/circuitbreaker:latest
    environment:
      - CB_ID=3
      - CB_IP=10.0.3.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30003
    networks:
      transportNetwork:
        ipv4_address: 10.0.3.2

  smartmeter4:
    image: jsandeuc3m/smartmeter:latest
    environment:
      - SM_ID=4
      - SM_IP=10.0.4.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORTV=10040
      - S_PORTI=20040
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.4.1

  circuitbreaker4:
    image: jsandeuc3m/circuitbreaker:latest
    environment:
      - CB_ID=4
      - CB_IP=10.0.4.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30004
    networks:
      transportNetwork:
        ipv4_address: 10.0.4.2

  smartmeter5:
    image: jsandeuc3m/smartmeter:latest
    environment:
      - SM_ID=5
      - SM_IP=10.0.5.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORTV=10050
      - S_PORTI=20050
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.5.1

  circuitbreaker5:
    image: jsandeuc3m/circuitbreaker:latest
    environment:
      - CB_ID=5
      - CB_IP=10.0.5.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30005
    networks:
      transportNetwork:
        ipv4_address: 10.0.5.2

  smartmeter6:
    image: jsandeuc3m/smartmeter:latest
    environment:
      - SM_ID=6
      - SM_IP=10.0.6.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORTV=10060
      - S_PORTI=20060
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.6.1

  circuitbreaker6:
    image: jsandeuc3m/circuitbreaker:latest
    environment:
      - CB_ID=6
      - CB_IP=10.0.6.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30006
    networks:
      transportNetwork:
        ipv4_address: 10.0.6.2

  smartmeter7:
    image: jsandeuc3m/smartmeter:latest
    environment:
      - SM_ID=7
      - SM_IP=10.0.7.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORTV=10060
      - S_PORTI=20060
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.7.1

  circuitbreaker7:
    image: jsandeuc3m/circuitbreaker:latest
    environment:
      - CB_ID=7
      - CB_IP=10.0.7.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30007
    networks:
      transportNetwork:
        ipv4_address: 10.0.7.2

  smartmeter8:
    image: jsandeuc3m/smartmeter:latest
    environment:
      - SM_ID=8
      - SM_IP=10.0.8.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORTV=10800
      - S_PORTI=20080
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.8.1

  circuitbreaker8:
    image: jsandeuc3m/circuitbreaker:latest
    environment:
      - CB_ID=8
      - CB_IP=10.0.8.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30008
    networks:
      transportNetwork:
        ipv4_address: 10.0.8.2

  smartmeter9:
    image: jsandeuc3m/smartmeter:latest
    environment:
      - SM_ID=9
      - SM_IP=10.0.9.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORTV=10090
      - S_PORTI=20090
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.9.1

  circuitbreaker9:
    image: jsandeuc3m/circuitbreaker:latest
    environment:
      - CB_ID=9
      - CB_IP=10.0.9.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30009
    networks:
      transportNetwork:
        ipv4_address: 10.0.9.2

  smartmeter10:
    image: jsandeuc3m/smartmeter:latest
    environment:
      - SM_ID=10
      - SM_IP=10.0.10.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORTV=10100
      - S_PORTI=20100
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.10.1

  circuitbreaker10:
    image: jsandeuc3m/circuitbreaker:latest
    environment:
      - CB_ID=10
      - CB_IP=10.0.10.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30010
    networks:
      transportNetwork:
        ipv4_address: 10.0.10.2

  smartmeter11:
    image: jsandeuc3m/smartmeter:latest
    environment:
      - SM_ID=11
      - SM_IP=10.0.11.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORTV=10110
      - S_PORTI=20110
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.11.1

  circuitbreaker11:
    image: jsandeuc3m/circuitbreaker:latest
    environment:
      - CB_ID=11
      - CB_IP=10.0.11.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30011
    networks:
      transportNetwork:
        ipv4_address: 10.0.11.2

  smartmeter12:
    image: jsandeuc3m/smartmeter:latest
    environment:
      - SM_ID=12
      - SM_IP=10.0.12.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORTV=10120
      - S_PORTI=20120
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.12.1

  circuitbreaker12:
    image: jsandeuc3m/circuitbreaker:latest
    environment:
      - CB_ID=12
      - CB_IP=10.0.12.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30012
    networks:
      transportNetwork:
        ipv4_address: 10.0.12.2

  smartmeter13:
    image: jsandeuc3m/smartmeter:latest
    environment:
      - SM_ID=13
      - SM_IP=10.0.13.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORTV=10130
      - S_PORTI=20130
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.13.1

  circuitbreaker13:
    image: jsandeuc3m/circuitbreaker:latest
    environment:
      - CB_ID=13
      - CB_IP=10.0.13.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30013
    networks:
      transportNetwork:
        ipv4_address: 10.0.13.2

  smartmeter14:
    image: jsandeuc3m/smartmeter:latest
    environment:
      - SM_ID=14
      - SM_IP=10.0.14.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORTV=10140
      - S_PORTI=20140
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.14.1

  circuitbreaker14:
    image: jsandeuc3m/circuitbreaker:latest
    environment:
      - CB_ID=14
      - CB_IP=10.0.14.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30014
    networks:
      transportNetwork:
        ipv4_address: 10.0.14.2

  smartmeter15:
    image: jsandeuc3m/smartmeter:latest
    environment:
      - SM_ID=15
      - SM_IP=10.0.15.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORTV=10150
      - S_PORTI=20150
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.15.1

  circuitbreaker15:
    image: jsandeuc3m/circuitbreaker:latest
    environment:
      - CB_ID=15
      - CB_IP=10.0.15.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30015
    networks:
      transportNetwork:
        ipv4_address: 10.0.15.2

networks:
  transportNetwork:
    driver: ipvlan
    driver_opts:
      parent: eth0
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1