services:

  smartmeter1:
    image: smartmeter:latest
    environment:
      - SM_ID=1
      - SM_IP=10.0.1.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10001
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.1.1

  circuitbreaker1:
    image: circuitbreaker:latest
    environment:
      - CB_ID=1
      - CB_IP=10.0.1.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30001
    networks:
      transportNetwork:
        ipv4_address: 10.0.1.2

  smartmeter2:
    image: smartmeter:latest
    environment:
      - SM_ID=2
      - SM_IP=10.0.2.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10002
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.2.1

  circuitbreaker2:
    image: circuitbreaker:latest
    environment:
      - CB_ID=2
      - CB_IP=10.0.2.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30002
    networks:
      transportNetwork:
        ipv4_address: 10.0.2.2

  smartmeter3:
    image: smartmeter:latest
    environment:
      - SM_ID=3
      - SM_IP=10.0.3.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10003
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.3.1

  circuitbreaker3:
    image: circuitbreaker:latest
    environment:
      - CB_ID=3
      - CB_IP=10.0.3.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30003
    networks:
      transportNetwork:
        ipv4_address: 10.0.3.2

  smartmeter4:
    image: smartmeter:latest
    environment:
      - SM_ID=4
      - SM_IP=10.0.4.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10004
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.4.1

  circuitbreaker4:
    image: circuitbreaker:latest
    environment:
      - CB_ID=4
      - CB_IP=10.0.4.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30004
    networks:
      transportNetwork:
        ipv4_address: 10.0.4.2

  smartmeter5:
    image: smartmeter:latest
    environment:
      - SM_ID=5
      - SM_IP=10.0.5.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10005
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.5.1

  circuitbreaker5:
    image: circuitbreaker:latest
    environment:
      - CB_ID=5
      - CB_IP=10.0.5.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30005
    networks:
      transportNetwork:
        ipv4_address: 10.0.5.2

  smartmeter6:
    image: smartmeter:latest
    environment:
      - SM_ID=6
      - SM_IP=10.0.6.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10006
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.6.1

  circuitbreaker6:
    image: circuitbreaker:latest
    environment:
      - CB_ID=6
      - CB_IP=10.0.6.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30006
    networks:
      transportNetwork:
        ipv4_address: 10.0.6.2

  smartmeter7:
    image: smartmeter:latest
    environment:
      - SM_ID=7
      - SM_IP=10.0.7.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10007
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.7.1

  circuitbreaker7:
    image: circuitbreaker:latest
    environment:
      - CB_ID=7
      - CB_IP=10.0.7.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30007
    networks:
      transportNetwork:
        ipv4_address: 10.0.7.2

  smartmeter8:
    image: smartmeter:latest
    environment:
      - SM_ID=8
      - SM_IP=10.0.8.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10008
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.8.1

  circuitbreaker8:
    image: circuitbreaker:latest
    environment:
      - CB_ID=8
      - CB_IP=10.0.8.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30008
    networks:
      transportNetwork:
        ipv4_address: 10.0.8.2

  smartmeter9:
    image: smartmeter:latest
    environment:
      - SM_ID=9
      - SM_IP=10.0.9.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10009
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.9.1

  circuitbreaker9:
    image: circuitbreaker:latest
    environment:
      - CB_ID=9
      - CB_IP=10.0.9.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30009
    networks:
      transportNetwork:
        ipv4_address: 10.0.9.2

  smartmeter10:
    image: smartmeter:latest
    environment:
      - SM_ID=10
      - SM_IP=10.0.10.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10010
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.10.1

  circuitbreaker10:
    image: circuitbreaker:latest
    environment:
      - CB_ID=10
      - CB_IP=10.0.10.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30010
    networks:
      transportNetwork:
        ipv4_address: 10.0.10.2

  smartmeter11:
    image: smartmeter:latest
    environment:
      - SM_ID=11
      - SM_IP=10.0.11.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10011
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.11.1

  circuitbreaker11:
    image: circuitbreaker:latest
    environment:
      - CB_ID=11
      - CB_IP=10.0.11.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30011
    networks:
      transportNetwork:
        ipv4_address: 10.0.11.2

  smartmeter12:
    image: smartmeter:latest
    environment:
      - SM_ID=12
      - SM_IP=10.0.12.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10012
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.12.1

  circuitbreaker12:
    image: circuitbreaker:latest
    environment:
      - CB_ID=12
      - CB_IP=10.0.12.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30012
    networks:
      transportNetwork:
        ipv4_address: 10.0.12.2

  smartmeter13:
    image: smartmeter:latest
    environment:
      - SM_ID=13
      - SM_IP=10.0.13.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10013
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.13.1

  circuitbreaker13:
    image: circuitbreaker:latest
    environment:
      - CB_ID=13
      - CB_IP=10.0.13.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30013
    networks:
      transportNetwork:
        ipv4_address: 10.0.13.2

  smartmeter14:
    image: smartmeter:latest
    environment:
      - SM_ID=14
      - SM_IP=10.0.14.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10014
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.14.1

  circuitbreaker14:
    image: circuitbreaker:latest
    environment:
      - CB_ID=14
      - CB_IP=10.0.14.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30014
    networks:
      transportNetwork:
        ipv4_address: 10.0.14.2

  smartmeter15:
    image: smartmeter:latest
    environment:
      - SM_ID=15
      - SM_IP=10.0.15.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10015
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.15.1

  circuitbreaker15:
    image: circuitbreaker:latest
    environment:
      - CB_ID=15
      - CB_IP=10.0.15.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30015
    networks:
      transportNetwork:
        ipv4_address: 10.0.15.2

  smartmeter16:
    image: smartmeter:latest
    environment:
      - SM_ID=16
      - SM_IP=10.0.16.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10016
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.16.1

  circuitbreaker16:
    image: circuitbreaker:latest
    environment:
      - CB_ID=16
      - CB_IP=10.0.16.2
      - CB_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_PORT=30016
    networks:
      transportNetwork:
        ipv4_address: 10.0.16.2

  smartmeter17:
    image: smartmeter:latest
    environment:
      - SM_ID=17
      - SM_IP=10.0.17.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10017
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.17.1

  smartmeter18:
    image: smartmeter:latest
    environment:
      - SM_ID=18
      - SM_IP=10.0.18.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10018
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.18.1

  smartmeter19:
    image: smartmeter:latest
    environment:
      - SM_ID=19
      - SM_IP=10.0.19.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10019
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.19.1

  smartmeter20:
    image: smartmeter:latest
    environment:
      - SM_ID=19
      - SM_IP=10.0.20.1
      - SM_GATEWAY=10.0.0.1
      - S_IP=10.0.0.2
      - S_DATA_PORT=10020
      - SAFE_THRESHOLD=500
    networks:
      transportNetwork:
        ipv4_address: 10.0.20.1

networks:
  transportNetwork:
    driver: ipvlan
    driver_opts:
      parent: eth0
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1